
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: callmanager
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"